export const films = [
    {
        id: 1,
        title: "Bullet science",
        image: "/src/assets/img/bullet_science.png",
        year: "2022",
        genre: "Action comedy",
        isFavorited: true,
        isTrend: false,
    },
    {
        id: 2,
        title: "House of Gucci",
        image: "/src/assets/img/house_of_gucci.png",
        year: "2022",
        genre: "Drama",
        isFavorited: true,
        isTrend: true,
    },
    {
        id: 3,
        title: "Tokyo Train",
        image: "/src/assets/img/tokyo_train.png",
        year: "2022",
        genre: "Action comedy",
        isFavorited: false,
        isTrend: true,
    },
    {
        id: 4,
        title: "Moonfall",
        image: "/src/assets/img/moonfall.png",
        year: "2022",
        genre: "Sci-fi",
        isFavorited: false,
        isTrend: true,
    },
    {
        id: 5,
        title: "Life in Paris",
        image: "/src/assets/img/life_in_paris.png",
        year: "2023",
        genre: "Documentary series",
        isFavorited: false,
        isTrend: true,
    },

];