export const films = [
    {
        id: 1,
        title: "Bullet science",
        image: "/src/assets/img/bullet_science.png",
        year: "2022",
        genre: "Action comedy",
        isFavorited: true,
        isTrend: false,
        isWatching: false,
        rating: 7.8,
        duration: "2h 38m",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam aliquam quaerat eligendi quas dolor ad voluptatibus sit libero vel facere pariatur nisi dolore, eveniet neque illo quidem sequi quo soluta!"
    },
    {
        id: 2,
        title: "House of Gucci",
        image: "/src/assets/img/house_of_gucci.png",
        year: "2022",
        genre: "Drama",
        isFavorited: true,
        isTrend: true,
        isWatching: false,
        rating: 7.8,
        duration: "2h 38m",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam aliquam quaerat eligendi quas dolor ad voluptatibus sit libero vel facere pariatur nisi dolore, eveniet neque illo quidem sequi quo soluta!"
    },
    {
        id: 3,
        title: "Tokyo Train",
        image: "/src/assets/img/tokyo_train.png",
        year: "2022",
        genre: "Action comedy",
        isFavorited: false,
        isTrend: true,
        isWatching: false,
        rating: 7.8,
        duration: "2h 38m",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam aliquam quaerat eligendi quas dolor ad voluptatibus sit libero vel facere pariatur nisi dolore, eveniet neque illo quidem sequi quo soluta!"
    },
    {
        id: 4,
        title: "Moonfall",
        image: "/src/assets/img/moonfall.png",
        year: "2022",
        genre: "Sci-fi",
        isFavorited: false,
        isTrend: true,
        isWatching: false,
        rating: 7.8,
        duration: "2h 38m",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam aliquam quaerat eligendi quas dolor ad voluptatibus sit libero vel facere pariatur nisi dolore, eveniet neque illo quidem sequi quo soluta!"
    },
    {
        id: 5,
        title: "Life in Paris",
        image: "/src/assets/img/life_in_paris.png",
        year: "2023",
        genre: "Documentary series",
        isFavorited: false,
        isTrend: true,
        isWatching: false,
        rating: 7.8,
        duration: "2h 38m",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam aliquam quaerat eligendi quas dolor ad voluptatibus sit libero vel facere pariatur nisi dolore, eveniet neque illo quidem sequi quo soluta!"
    },
    {
        id: 6,
        image: "/src/assets/img/love.png",
        isWatching: true,
    },
    {
        id: 7,
        image: "/src/assets/img/skateboard.png",
        isWatching: true,
    },
    {
        id: 8,
        image: "/src/assets/img/space.png",
        isWatching: true,
    },
    {
        id: 9,
        title: "Insider",
        image: "/src/assets/img/insider.png",
        year: "2022",
        genre: "Comedy horror",
        isFavorited: false,
        isTrend: false,
        isWatching: false,
    },

];